### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by tugcekeser** [tugcekeser/NYTimesArticleSearch#2]
![demo_article_search](https://cloud.githubusercontent.com/assets/17666583/19673450/b20c446e-9a34-11e6-97d3-b593ae0c8009.gif)

**Comment by codepathreview** [comment]
Hello Rabia,

Looks like your submitted Github repo is missing some of the app code. Please [push your code to Github](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-pushing-code) and then [re-submit your project](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-submitting-through-course-system) through the course system.
